### ISSUE TITLE
Allow parsing mail directly from string

### ISSUE THREAD

**Issue by caugner** [zbateson/MailMimeParser#18]
**Background**: I have emails that I fetch from a database rather than from files.

**Problem**: It is not currently possible to parse a mail directly from a string (as far as I can see from both the [code](https://github.com/zbateson/MailMimeParser/blob/master/src/MessageParser.php#L60-L65) and the [Usage Guide](https://github.com/zbateson/MailMimeParser/wiki/Usage-Guide)).

**Solution**: Add a *#parseString* method to the  `MailMimeParser`:

```php
$mailParser = new MailMimeParser();
$message = mailParser->parseString($mailAsString);
```

**Appendix**: Ideally the `Message` could also have a static convenience method *#fromString* (*):
```php
$message = Message::fromString($mailAsString)
```

(*) = It could simply instantiate an `MailMimeParser` for me, as I don't need that afterwards anyway.

**Comment by zbateson** [comment]
Hi @caugner --

Fair point -- it would be a useful addition.  I'm working on some other features so will try including in my end-of-August release :)

In the meantime it is possible to do by creating a php://memory stream and writing to it.  A bit silly because it would probably use double the memory internally... if I can think of a clever way I may write a way around that but because my library is so stream-dependent I may just wrap a parseString (#fromString) into a memory or temp stream anyway.

All the best!

**Comment by postme** [comment]
Hi,

I'm using the following to parse directely from string:

```
$input = "This is the string";
$mailParser = new \ZBateson\MailMimeParser\MailMimeParser();
$handle = fopen('data://text/plain,' . $input, 'r');    
$message = $mailParser->parse($handle);
fclose($handle);
```

Hope this helps
Meint

**Comment by zbateson** [comment]
Pushed to master in 0.3.0

**Comment by zbateson** [comment]
Can now call ``` Message::from($string); ``` or ``` $mmp->parse($string); ``` for convenience.
