### ISSUE TITLE
text/rtf

### ISSUE THREAD

**Issue by vvv476** [zbateson/MailMimeParser#23]
If the email contains an attachment type text/rtf, then there is the unnecessary conversion encoding.
The problem is here:
PartStreamRegistry.php
`    private function attachCharsetFilterToStream(MimePart $part, $handle)
    {
        $contentType = strtolower($part->getHeaderValue('Content-Type', 'text/plain'));
        if (strpos($contentType, 'text/') === 0) {
`
Fix:
`        if ($contentType === 'text/plain' || $contentType === 'text/html') {
`

**Comment by zbateson** [comment]
Hi @vvv476 - good point, thank you!  There may be other text/* cases that do warrant the charset filter, and there may be other negative effects elsewhere for a text/rtf attachment.  I will investigate and give it some thought in the next few days.

**Comment by zbateson** [comment]
Hi @vvv476 ,

Fixed in the just released 0.3.2 :) please reopen/let me know if you have any issues.

My solution was to apply charset filters to text/plain text/html, and any text/* mime type that also has a charset filter.  The charset filter can be manually applied otherwise if wanted, so hopefully this is sufficient!

Thanks again!
