### ISSUE TITLE
getTextContent doesnt retrieve body of digest-multipart message

### ISSUE THREAD

**Issue by postme** [zbateson/MailMimeParser#28]
[[17]-multipart-digest.txt](https://github.com/zbateson/MailMimeParser/files/671743/17.-multipart-digest.txt)

nor does getHtmlContent()

message format of multipart-digest is weird, looks like it isn't being recognized as either text/plain or text/html?

**Comment by zbateson** [comment]
Hi @postme -- unfortunately I haven't built support for multipart/digest.  I'll investigate and add it in there in the coming couple of weeks hopefully :smile:

**Comment by zbateson** [comment]
Hi @postme --

Sorry for the delay on this one.  Just got a chance to look more closely.  The content type is message/rfc822 in this case which just means it contains an email.  It won't parse the email directly, but you could pass the embedded email onto MMP by reading its content:

```
// parsed into $message
$embeddedMessage = Message::from($message->getContentResourceHandle());
```
$embeddedMessage would then contain a Message object.  Even if the embedded message had a text/plain or text/html part, it would not be part of the main message's parts however, since it logically isn't.

Also, in the example you passed there aren't any further text/plain or text/html parts but maybe you're more wondering about 'how to get at the content' since it's not a text/plain or text/html part :)

Hopefully that clarifies things, but let me know if you have any further questions of course or close if satisfied.

All the best!

**Comment by zbateson** [comment]
Hi @postme 

I think this one's a non-issue, but please feel free to reopen of course if you disagree or want more info :smile:
