### ISSUE TITLE
Part with quoted printable encoding that is not really encoded

### ISSUE THREAD

**Issue by shotap** [zbateson/MailMimeParser#31]
Hi, I have a mail part that has a header
```Content-transfer-encoding: Quoted-Printable```
but the content is not really encoded as  quoted printable, when I do ```$part->getContent()``` I get empty content.
How can I fix it. Thanks

**Comment by zbateson** [comment]
Hi @shotap -

Hmmm... I'm not sure that would cause a completely empty email though it should be fine.  What version of mailmimeparser are you using and would it be possible to send me a copy to zbateson at gmail or attach it here?

Thank you

**Comment by shotap** [comment]
Hi, Im using version 0.4.0
the issue is that part has an header ```Content-transfer-encoding: Quoted-Printable``` but the part is not really Quoted-Printable. so the part content that I get is empty.

**Comment by zbateson** [comment]
Hi @shotap 

In testing, I've had no problem reading an email that claimed to be "Quoted-Printable" but in fact wasn't.  My test simply involved changing the non-quoted-printable email file under tests/_data/m0009.txt to have an additional "Content-Transfer-Encoding: quoted-printable" and re-test

``` ./vendor/bin/phpunit -c ./tests/phpunit.xml --filter=m0009
PHPUnit 5.0.8 by Sebastian Bergmann and contributors.

.                                                                   1 / 1 (100%)

Time: 70 ms, Memory: 8.50Mb
```

Perhaps the problem is encoding related, or something special about the message itself that would cause it to fail being read as 'quoted-printable'.

**Comment by zbateson** [comment]
Could it be your /tmp folder isn't large enough as well?  Check out #32

**Comment by zbateson** [comment]
Please reopen if this is still an issue and there's more info.

Thanks,
Zaahid

**Comment by shotap** [comment]
This was my fault, you lib is great!
