### ISSUE TITLE
Attachment parts dont want to show up

### ISSUE THREAD

**Issue by pytnik89** [zbateson/MailMimeParser#35]
I want to parse simple mail, when I try to attach img $message->getAttachmentPart(0) gives me correct attachment part and all is fine, but when I did it for ics file attachment It gives me no results, what am I doing wrong? I have attached example of such file to my question, sorry for being boring due to my misunderstanding.

[mail_body.txt](https://github.com/zbateson/MailMimeParser/files/823702/mail_body.txt)

**Comment by zbateson** [comment]
Hi @pytnik89 --

That one's a special case in that it's neither an attachment nor the main part of the content... and the message is not a multipart/alternative.  I'm working on better handling cases like these (your issue is the 3rd in a few weeks about it all of a sudden!)

Anyway, you should be able to get at it by calling ``` $message->getTextPart(); ```

All the best,
Zaahid

**Comment by pytnik89** [comment]
Thx a lot for u explanation, hope this will be fixed or solved in some way soon. This question cab be closed.
