### ISSUE TITLE
Some emails sent from IBM Notes not parsed

### ISSUE THREAD

**Issue by yurikuzn** [zbateson/MailMimeParser#55]
Hi,

It could be caused by some not printable characters, but I'm not sure.

Raw contents of the email:
[problem-email-original.txt](https://github.com/zbateson/MailMimeParser/files/1460994/problem-email-original.txt)

Thanks

**Comment by zbateson** [comment]
Hmmmm, that's an interesting way of splitting boundary in the Content-Type header's boundary value.  Because it's in double-quotes, I wonder if I may be considering that a "literal" space or how I'm handling that.  Apart from that the message looks normal enough to me...

Can you tell me what you're expecting and how it's failling?  Is it throwing out an error, or just considering the whole document one part, or what's happening with it?  The part of the code that's failing e.g. if you're calling "getTextContent" or something could be helpful too :blush: 

Thanks

**Comment by yurikuzn** [comment]
It doesn't return content. Emails are fetched with empty body. No error thrown.

I've encountered with boudary values containing line breaks before, when utilized zend mail library. I remember there was a problem with parcing too.

**Comment by zbateson** [comment]
Thanks @yurikuzn -- this highlighted an issue with parsing quoted header parts.  My implementation considered the new line to be a valid part of the quoted part and kept it, but should actually be ignored  based on the example here: https://tools.ietf.org/html/rfc822#section-3.1.1 and here https://www.w3.org/Protocols/rfc1341/7_2_Multipart.html in 7.2.1.

I've pushed a fix to 'master'.  Please let me know if you notice any issues... otherwise I'll push a new release version in a couple of days :blush:

**Comment by yurikuzn** [comment]
Thank you
