### ISSUE TITLE
lack of uuencode

### ISSUE THREAD

**Issue by barszpaw** [zbateson/MailMimeParser#56]
Hi,
In file  MailMimeParser/src/Stream/PartStreamRegistry.php 'uudecode' is missing.
Daetails:
ZBateson\MailMimeParser\Stream::attachEncodingFilterToStream();
is

```php
case 'x-uudecode':
         stream_filer_
```
should be
```php
 case 'x-uuencode':
 case 'uuencode':
            stream_filter_
```
Could you correct this issue?

**Comment by zbateson** [comment]
Hi @barszpaw,

Thanks for the suggestion.  Looking around at other implementations I see Python's mimetools library supports all of these: uuencode, x-uuencode, uue, x-uue

I'm assuming the creator's of the mimetools library saw those being used in enough places to warrant implementing them as acceptable... unless anyone else objects here, I'll go ahead with that for the next release (will target first of the month).

**Comment by zbateson** [comment]
Released in 0.4.7

**Comment by barszpaw** [comment]
Thank you for this fix. 
I wonder if is any way to set or auto detect codepage of body mail or attachment ? In my program I use this: iconv('windows-1250', 'utf-8',convert_uudecode($buffer))  but this solution is only for codepage windows-1250.

**Comment by zbateson** [comment]
No problem at all.

It might be that you needed to do that because the content wasn't being "transfer-encoding" decoded.  MailMimeParser should both uudecode and convert to UTF-8 automatically based on Transfer-Encoding header and the charset property of the Content-Type header... but if it didn't uudecode, charset conversion wouldn't work on the uuencoded bytes.
